### ISSUE TITLE
cider-repl-buffer-size-limit of 100 makes even relatively small values impossible to print

### ISSUE THREAD

**Issue by tekacs** [practicalli/spacemacs-config#4]
The update over here:

https://github.com/practicalli/spacemacs.d/commit/c48d5f9ab07d97f9378487c84d5d648b2598faea#diff-82c647c7e6a8e02d1b94a30268eb483ff5aadf926762a759fcd0f4c5850356bfR66

Introduces a limit of 100 on the REPL buffer size. Whilst `(comment ...` blocks and pretty printing in regions (`, e p f`, etc.) works well for many purposes, sometimes it's helpful to be able to print values in the REPL.

With the limit this low, a return value that's even a couple of lines long breaks through the limit and results in CIDER immediately clearing the REPL buffer before the value can print (in my configuration).

Happy to provide more context if this isn't replicable. :)

**Comment by practicalli-johnny** [comment]
Printing results in the REPL buffer seems to be very inefficient in Emacs and can cause significant slowdown over time.

Most of the questions I have seen about Emacs slowing down seem to be due to the REPL buffer.

The cider-inspect tool is significantly more efficient at showing results, especially paging through larger data sets and navigating nested structures.

If you feel there are still good reasons to evaluate results in the REPL, can you advise on a suitable value?

The only time I use the REPL buffer is for new Clojure server-side web-apps, just to display printlin log statement until I get a proper logging system set up.  So I am not a good candidate to know what value is best.

I would like to keep it as low as possible, but without breaking workflows.

Thank you.

**Comment by practicalli-johnny** [comment]
No suggestions as to an alternative value have been suggested, so will keep the default setting as 100.  This seems acceptable for minimal use of the REPL buffer.

If experiencing issues, then CIDER inspect should be used and logging should be viewed outside of Emacs or in a buffer set to fundamental-mode to avoid performance issues.
